spring:
  mongodb:
    username: sa
    password: Passw0rd
    host: localhost
    port: 27017
    database: AvisDatabase
    authentication-database: admin
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23li4anLDfrnOV1k16
            clientSecret: 6ae856a0316879acbe6f98f8fa1eec197fee7523
            scope: user:email
        provider:
          github:
            authorizationUri: https://github.com/login/oauth/authorize
            tokenUri: https://github.com/login/oauth/access_token
            userInfoUri: https://api.github.com/user
            userNameAttribute: id