spring:
  mongodb:
    username: sa
    password: Passw0rd
    host: localhost
    port: 27017
    database: AvisDatabase
    authentication-database: admin
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: YOUR_GITHUB_CLIENT_ID
            clientSecret: YOUR_GITHUB_CLIENT_SECRET
            scope: user:email
        provider:
          github:
            authorizationUri: https://github.com/login/oauth/authorize
            tokenUri: https://github.com/login/oauth/access_token
            userInfoUri: https://api.github.com/user
            userNameAttribute: id